apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  labels:
    run: zipkin-server
spec:
  ports:
  - name: port1
    protocol: TCP
    port: 9411
    nodePort: 30411
  selector:
    run: zipkin-service
  type: NodePort
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: zipkin-service
  labels:
    run: zipkin-service
spec:
  selector:
   matchLabels:
     run: zipkin-service 
  replicas: 1
  template:
    metadata:
      labels:
        run: zipkin-service
    spec:
      containers:
      - name: zipkin-service
        image: art.local:8081/docker-local/guestbook-microservices-k8s/zipkin-service:latest
        env:
          - name: ZIPKIN_SERVER
            value: "192.168.99.100"
          - name: ZIPKIN_SERVER_PORT
            value: "30411"
        ports:
        - containerPort: 9411
          protocol: TCP
      imagePullSecrets:
      - name: regcred-local
#TODO have issue in K8S
